services:
  node-application:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: rtmp-api
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage/
      - ./logs:/app/logs
      - ./certs:/app/certs
